2023-02-17 06:49:54,202 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Configure stats pid to 1159
2023-02-17 06:49:54,202 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/.config/wandb/settings
2023-02-17 06:49:54,202 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/settings
2023-02-17 06:49:54,202 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-17 06:49:54,203 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-17 06:49:54,203 INFO    MainThread:1159 [wandb_init.py:_log_setup():478] Logging user logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_064954-ubacfpos/logs/debug.log
2023-02-17 06:49:54,203 INFO    MainThread:1159 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_064954-ubacfpos/logs/debug-internal.log
2023-02-17 06:49:54,203 INFO    MainThread:1159 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7ff744f6d550>
2023-02-17 06:49:54,205 INFO    MainThread:1159 [wandb_init.py:init():518] calling init triggers
2023-02-17 06:49:54,205 INFO    MainThread:1159 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-17 06:49:54,205 INFO    MainThread:1159 [wandb_init.py:init():571] starting backend
2023-02-17 06:49:54,205 INFO    MainThread:1159 [wandb_init.py:init():575] setting up manager
2023-02-17 06:49:54,216 INFO    MainThread:1159 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-02-17 06:49:54,222 INFO    MainThread:1159 [wandb_init.py:init():582] backend started and connected
2023-02-17 06:49:54,236 INFO    MainThread:1159 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-17 06:49:54,236 INFO    MainThread:1159 [wandb_init.py:init():670] updated telemetry
2023-02-17 06:49:54,237 INFO    MainThread:1159 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-17 06:49:57,297 WARNING MsgRouterThr:1159 [router.py:message_loop():77] message_loop has been closed
2023-02-17 06:50:04,320 ERROR   MainThread:1159 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 713, in init
    result = run_init_handle.wait(
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Configure stats pid to 1159
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/.config/wandb/settings
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/settings
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_init.py:_log_setup():478] Logging user logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_065033-alf4l803/logs/debug.log
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_065033-alf4l803/logs/debug-internal.log
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_init.py:init():518] calling init triggers
2023-02-17 06:50:33,182 INFO    MainThread:1159 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-17 06:50:33,183 INFO    MainThread:1159 [wandb_init.py:init():571] starting backend
2023-02-17 06:50:33,183 INFO    MainThread:1159 [wandb_init.py:init():575] setting up manager
2023-02-17 06:50:33,196 ERROR   MainThread:1159 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Configure stats pid to 1159
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/.config/wandb/settings
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/settings
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_init.py:_log_setup():478] Logging user logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_065127-1jndpmsg/logs/debug.log
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_065127-1jndpmsg/logs/debug-internal.log
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_init.py:init():518] calling init triggers
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-17 06:51:27,118 INFO    MainThread:1159 [wandb_init.py:init():571] starting backend
2023-02-17 06:51:27,119 INFO    MainThread:1159 [wandb_init.py:init():575] setting up manager
2023-02-17 06:51:27,129 ERROR   MainThread:1159 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-02-17 06:56:09,279 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Configure stats pid to 1159
2023-02-17 06:56:09,279 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/.config/wandb/settings
2023-02-17 06:56:09,279 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/settings
2023-02-17 06:56:09,280 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-17 06:56:09,280 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-17 06:56:09,280 INFO    MainThread:1159 [wandb_init.py:_log_setup():478] Logging user logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_065609-uxk790i3/logs/debug.log
2023-02-17 06:56:09,280 INFO    MainThread:1159 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_065609-uxk790i3/logs/debug-internal.log
2023-02-17 06:56:09,280 INFO    MainThread:1159 [wandb_init.py:init():518] calling init triggers
2023-02-17 06:56:09,280 INFO    MainThread:1159 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-17 06:56:09,280 INFO    MainThread:1159 [wandb_init.py:init():571] starting backend
2023-02-17 06:56:09,281 INFO    MainThread:1159 [wandb_init.py:init():575] setting up manager
2023-02-17 06:56:09,291 ERROR   MainThread:1159 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-02-17 07:06:56,876 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Configure stats pid to 1159
2023-02-17 07:06:56,877 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/.config/wandb/settings
2023-02-17 07:06:56,877 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/settings
2023-02-17 07:06:56,877 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-17 07:06:56,877 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-17 07:06:56,877 INFO    MainThread:1159 [wandb_init.py:_log_setup():478] Logging user logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_070656-mkgkaon0/logs/debug.log
2023-02-17 07:06:56,877 INFO    MainThread:1159 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_070656-mkgkaon0/logs/debug-internal.log
2023-02-17 07:06:56,878 INFO    MainThread:1159 [wandb_init.py:init():518] calling init triggers
2023-02-17 07:06:56,878 INFO    MainThread:1159 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-17 07:06:56,878 INFO    MainThread:1159 [wandb_init.py:init():571] starting backend
2023-02-17 07:06:56,878 INFO    MainThread:1159 [wandb_init.py:init():575] setting up manager
2023-02-17 07:06:56,889 ERROR   MainThread:1159 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-02-17 07:11:08,927 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Configure stats pid to 1159
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/.config/wandb/settings
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/settings
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_init.py:_log_setup():478] Logging user logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_071108-177blrub/logs/debug.log
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_071108-177blrub/logs/debug-internal.log
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():518] calling init triggers
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():571] starting backend
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():575] setting up manager
2023-02-17 07:11:08,939 ERROR   MainThread:1159 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
