2023-02-17 07:11:08,927 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Configure stats pid to 1159
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/.config/wandb/settings
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/settings
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-17 07:11:08,928 INFO    MainThread:1159 [wandb_init.py:_log_setup():478] Logging user logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_071108-177blrub/logs/debug.log
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/adamelshimi/Desktop/Desktop - Adam’s MacBook Air/Udacity/MLDevOps/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/wandb/run-20230217_071108-177blrub/logs/debug-internal.log
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():518] calling init triggers
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():571] starting backend
2023-02-17 07:11:08,929 INFO    MainThread:1159 [wandb_init.py:init():575] setting up manager
2023-02-17 07:11:08,939 ERROR   MainThread:1159 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 576, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/adamelshimi/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
